Зданаие к методичке 6

Задание 2

In [5]:
import numpy as np

In [4]:
A = np.array([[3, -1, 1], [2, -5, -3], [1, 1, -1]])
b = np.array([4, -17, 0])
A_ext = np.column_stack([A, b])

rank_A = np.linalg.matrix_rank(A)
rank_A_ext = np.linalg.matrix_rank(A_ext)
n = len(A[0])

print(f'A:\n{A}\n')
print(f'A_ext:\n{A_ext}\n')

print(f'rank(A): {rank_A}\n')
print(f'rank(A_ext): {rank_A_ext}\n')
print(f'# of vars: {n}\n')

if rank_A == rank_A_ext == n:
    print(f'Система имеет единственное решение.')
elif rank_A == rank_A_ext < n:
    print(f'Система имеет бесконечное кол-во решений.')
elif rank_A < rank_A_ext:
    print(f'Система несовместна.')

A:
[[ 3 -1  1]
 [ 2 -5 -3]
 [ 1  1 -1]]

A_ext:
[[  3  -1   1   4]
 [  2  -5  -3 -17]
 [  1   1  -1   0]]

rank(A): 3

rank(A_ext): 3

# of vars: 3

Система имеет единственное решение.


In [6]:
A = np.array([[2, -4, 6], [1, -2, 3], [3, -6, 9]])
b = np.array([1, -2, 5])
A_ext = np.column_stack([A, b])

rank_A = np.linalg.matrix_rank(A)
rank_A_ext = np.linalg.matrix_rank(A_ext)
n = len(A[0])

print(f'A:\n{A}\n')
print(f'A_ext:\n{A_ext}\n')

print(f'rank(A): {rank_A}\n')
print(f'rank(A_ext): {rank_A_ext}\n')
print(f'# of vars: {n}\n')

if rank_A == rank_A_ext == n:
    print(f'Система имеет единственное решение.')
elif rank_A == rank_A_ext < n:
    print(f'Система имеет бесконечное кол-во решений.')
elif rank_A < rank_A_ext:
    print(f'Система несовместна.')

A:
[[ 2 -4  6]
 [ 1 -2  3]
 [ 3 -6  9]]

A_ext:
[[ 2 -4  6  1]
 [ 1 -2  3 -2]
 [ 3 -6  9  5]]

rank(A): 1

rank(A_ext): 2

# of vars: 3

Система несовместна.


In [7]:
A = np.array([[1, 2, 5], [3, 1, -8]])
b = np.array([4, -2])
A_ext = np.column_stack([A, b])

rank_A = np.linalg.matrix_rank(A)
rank_A_ext = np.linalg.matrix_rank(A_ext)
n = len(A[0])

print(f'A:\n{A}\n')
print(f'A_ext:\n{A_ext}\n')

print(f'rank(A): {rank_A}\n')
print(f'rank(A_ext): {rank_A_ext}\n')
print(f'# of vars: {n}\n')

if rank_A == rank_A_ext == n:
    print(f'Система имеет единственное решение.')
elif rank_A == rank_A_ext < n:
    print(f'Система имеет бесконечное кол-во решений.')
elif rank_A < rank_A_ext:
    print(f'Система несовместна.')

A:
[[ 1  2  5]
 [ 3  1 -8]]

A_ext:
[[ 1  2  5  4]
 [ 3  1 -8 -2]]

rank(A): 2

rank(A_ext): 2

# of vars: 3

Система имеет бесконечное кол-во решений.


Задание 3

In [8]:
A = np.array([[1, 3, -2, 4], [0, 5, 0, 1], [0, 0, 3, 0], [0, 0, 0, 2]])
b = np.array([3, 2, 4, 1])
A_ext = np.column_stack([A, b])

rank_A = np.linalg.matrix_rank(A)
rank_A_ext = np.linalg.matrix_rank(A_ext)
n = len(A[0])

print(f'A:\n{A}\n')
print(f'A_ext:\n{A_ext}\n')

print(f'rank(A): {rank_A}\n')
print(f'rank(A_ext): {rank_A_ext}\n')
print(f'# of vars: {n}\n')

if rank_A == rank_A_ext == n:
    print(f'Система имеет единственное решение.')
elif rank_A == rank_A_ext < n:
    print(f'Система имеет бесконечное кол-во решений.')
elif rank_A < rank_A_ext:
    print(f'Система несовместна.')

A:
[[ 1  3 -2  4]
 [ 0  5  0  1]
 [ 0  0  3  0]
 [ 0  0  0  2]]

A_ext:
[[ 1  3 -2  4  3]
 [ 0  5  0  1  2]
 [ 0  0  3  0  4]
 [ 0  0  0  2  1]]

rank(A): 4

rank(A_ext): 4

# of vars: 4

Система имеет единственное решение.


Задание к методичке 7

In [9]:
import scipy.linalg

Задание 1.a)

In [10]:
A = np.array([[1, -2], [3, -4]])
b = np.array([1, 7])

det_A = np.linalg.det(A)

print(f'A:\n{A}\n')
print(f'b:\n{b}\n')

print(f'det(A): {det_A}\n')

if det_A != 0:
    print(f'Определитель матрицы квадратной системы не равен 0, система совместна и имеет единственное решение.\n')

A1 = np.column_stack([b, A[:, 1]])
det_A1 = np.linalg.det(A1)

print(f'A1:\n{A1}\n')
print(f'det(A1): {det_A1}\n')

A2 = np.column_stack([A[:, 0], b])
det_A2 = np.linalg.det(A2)

print(f'A2:\n{A2}\n')
print(f'det(A2): {det_A2}\n')

print(f'x1 = {det_A1 / det_A}')
print(f'x2 = {det_A2 / det_A}')

A:
[[ 1 -2]
 [ 3 -4]]

b:
[1 7]

det(A): 2.0000000000000004

Определитель матрицы квадратной системы не равен 0, система совместна и имеет единственное решение.

A1:
[[ 1 -2]
 [ 7 -4]]

det(A1): 9.999999999999998

A2:
[[1 1]
 [3 7]]

det(A2): 3.999999999999999

x1 = 4.999999999999998
x2 = 1.9999999999999991


Задание 1.б)

In [11]:
A = np.array([[2, -1, 5], [1, 1, -3], [2, 4, 1]])
b = np.array([10, -2, 1])

det_A = np.linalg.det(A)

print(f'A:\n{A}\n')
print(f'b:\n{b}\n')

print(f'det(A): {det_A}\n')

if det_A != 0:
    print(f'Определитель матрицы квадратной системы не равен 0, система совместна и имеет единственное решение.\n')

A1 = np.column_stack([b, A[:, 1:]])
det_A1 = np.linalg.det(A1)

print(f'A1:\n{A1}\n')
print(f'det(A1): {det_A1}\n')

A2 = np.column_stack([A[:, 0], b, A[:, 2]])
det_A2 = np.linalg.det(A2)

print(f'A2:\n{A2}\n')
print(f'det(A2): {det_A2}\n')

A3 = np.column_stack([A[:, 0:2], b])
det_A3 = np.linalg.det(A3)

print(f'A3:\n{A3}\n')
print(f'det(A3): {det_A3}\n')

print(f'x1 = {det_A1 / det_A}')
print(f'x2 = {det_A2 / det_A}')
print(f'x3 = {det_A3 / det_A}')

A:
[[ 2 -1  5]
 [ 1  1 -3]
 [ 2  4  1]]

b:
[10 -2  1]

det(A): 42.99999999999998

Определитель матрицы квадратной системы не равен 0, система совместна и имеет единственное решение.

A1:
[[10 -1  5]
 [-2  1 -3]
 [ 1  4  1]]

det(A1): 86.00000000000004

A2:
[[ 2 10  5]
 [ 1 -2 -3]
 [ 2  1  1]]

det(A2): -43.000000000000014

A3:
[[ 2 -1 10]
 [ 1  1 -2]
 [ 2  4  1]]

det(A3): 42.99999999999998

x1 = 2.0000000000000018
x2 = -1.0000000000000009
x3 = 1.0


Задание 3

In [24]:
from scipy.linalg import lu, lu_factor, lu_solve

In [26]:
A = np.array([[2, 1, 3], [11, 7, 5], [9, 8, 4]])
b = np.array([1, -6, -5])

lu, piv = scipy.linalg.lu_factor(A)
x = scipy.linalg.lu_solve((lu, piv), b)

print(f'A:\n{A}\n')
print(f'b:\n{b}\n')
print(f'x:\n{x}\n')
print(f'Ax:\n{A @ x}\n')
print(f'Ax - b:\n{A @ x - b}\n')

print(f'lu:\n{lu}\n')
print(f'piv:\n{piv}\n')

A:
[[ 2  1  3]
 [11  7  5]
 [ 9  8  4]]

b:
[ 1 -6 -5]

x:
[-1.  0.  1.]

Ax:
[ 1. -6. -5.]

Ax - b:
[0. 0. 0.]

lu:
[[11.          7.          5.        ]
 [ 0.81818182  2.27272727 -0.09090909]
 [ 0.18181818 -0.12        2.08      ]]

piv:
[1 2 2]



Задание 4

In [27]:
A = np.array([[81, -45, 45], [-45, 50, -15], [45, -15, 38]])
b = np.array([531, -460, 193])

K = scipy.linalg.cho_factor(A)
x = scipy.linalg.cho_solve(K, b)

print(f'A:\n{A}\n')
print(f'K:\n{K}\n')
print(f'b:\n{b}\n')
print(f'x:\n{x}\n')
print(f'Ax:\n{A @ x}\n')
print(f'Ax - b:\n{A @ x - b}\n')

A:
[[ 81 -45  45]
 [-45  50 -15]
 [ 45 -15  38]]

K:
(array([[  9.,  -5.,   5.],
       [-45.,   5.,   2.],
       [ 45., -15.,   3.]]), False)

b:
[ 531 -460  193]

x:
[ 6. -5. -4.]

Ax:
[ 531. -460.  193.]

Ax - b:
[0. 0. 0.]



Задание 5