Дз к методичке 3

1. Установить, какие произведения матриц  AB  и  BA  определены, и найти размерности полученных матриц:

а)  A  — матрица  4×2 ,  B  — матрица  4×2 ;

б)  A  — матрица  2×5 ,  B  — матрица  5×3 ;

в)  A  — матрица  8×3 ,  B  — матрица  3×8 ;

г)  A  — квадратная матрица  4×4 ,  B  — квадратная матрица  4×4 .



а) перемножить нельзя б) AB 2х3 в) AB 8х8, BA 3х3 г)AB BA 4х4

2. Найти сумму и произведение матриц.

In [4]:
import numpy as np


In [5]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])
print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
print(f'Матрица C = A + B\n{A + B}')
print(f'Матрица AB\n{np.dot(A, B)}')
print(f'Матрица BA\n{np.dot(B, A)}')

Матрица A
[[ 1 -2]
 [ 3  0]]
Матрица B
[[ 4 -1]
 [ 0  5]]
Матрица C = A + B
[[ 5 -3]
 [ 3  5]]
Матрица AB
[[  4 -11]
 [ 12  -3]]
Матрица BA
[[ 1 -8]
 [15  0]]


3. Вычислить линейную комбинацию  3A−2B+4C

In [6]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])
print(f'Матрица 3A-2B+4C\n{3*A-2*B+4*C}')

Матрица 3A-2B+4C
[[ 11  -5]
 [  9 -12]]


4.

In [7]:
A = np.array([[4, 1], [5, -2], [2, 3]])
print(f'Матрица:\n{A}')
print(f'Транспонированная матрица:\n{A.T}')
print(f'Матрица A*AT\n{np.dot(A, A.T)}')
print(f'Матрица A\n{np.dot(A.T, A)}')

Матрица:
[[ 4  1]
 [ 5 -2]
 [ 2  3]]
Транспонированная матрица:
[[ 4  5  2]
 [ 1 -2  3]]
Матрица A*AT
[[17 18 11]
 [18 29  4]
 [11  4 13]]
Матрица A
[[45  0]
 [ 0 14]]


Дз к методичке 4

4.

In [8]:
import numpy as np

In [9]:
x = [1, 2, 3]
y = [1, 1, 1]
z = [2, 3, 4]

a = np.array([x, y, z])
r = np.linalg.matrix_rank(a)

print(f'Ранг матрицы: {r}')

Ранг матрицы: 2


In [10]:
x = [0, 0, 2, 1]
y = [0, 0, 2, 2]
z = [0, 0, 4, 3]
z = [2, 3, 5, 6]

a = np.array([x, y, z])
r = np.linalg.matrix_rank(a)

print(f'Ранг матрицы: {r}')

Ранг матрицы: 3
